GET http://localhost:5000/users
Authorization: Bearer
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJSYWZpIEFudGFyZXNhIiwiZW1haWwiOiJyYWZpQGdtYWlsLmNvbSIsImlhdCI6MTcwMTcwODk0MywiZXhwIjoxNzAxNzA4OTYzfQ.O75vQ3bfiZb2VvrmGxfpoDn8mEqjyUyTokF0_nadYJQ

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Rafi Antaresa",
    "email": "rafi@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "rafi@gmail.com",
    "password": "123456"
}

###
GET  http://localhost:5000/token

###
DELETE http://localhost:5000/logout